//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EForms_Admin_Users
    {
        public int Admin_UID { get; set; }
        public string FormName { get; set; }
        public string Network_User_ID { get; set; }
        public Nullable<int> County_FK { get; set; }
        public Nullable<bool> ActiveFlag { get; set; }
    }
}
