//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        public int PurchaseOrder_PK { get; set; }
        public string CountyName { get; set; }
        public Nullable<System.DateTime> DateRequested { get; set; }
        public Nullable<System.DateTime> DateNeeded { get; set; }
        public string Program { get; set; }
        public string BudgetNumber { get; set; }
        public string VendorName { get; set; }
        public string VendorPhone { get; set; }
        public string VendorAddress { get; set; }
        public string VendorCity { get; set; }
        public string VendorState { get; set; }
        public string VendorZip { get; set; }
        public string EmployeeName { get; set; }
        public string RequesterNetworkID { get; set; }
        public string SuperID { get; set; }
        public string DirectorID { get; set; }
        public Nullable<System.DateTime> RequesterApprovalDt { get; set; }
        public Nullable<System.DateTime> SupervisorApprovalDt { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> DirectorApprovalDt { get; set; }
        public string CurrentRequestStatus { get; set; }
        public string SuperExplain { get; set; }
        public string GeneralComments { get; set; }
        public string ObligationNumber { get; set; }
        public Nullable<int> WorkOrder_FK { get; set; }
        public Nullable<int> Cost_FK { get; set; }
        public Nullable<System.DateTime> APProcessedDt { get; set; }
        public string APProcessedBy { get; set; }
        public string APComments { get; set; }
        public string AlsoNotify { get; set; }
        public string Instructions { get; set; }
    }
}
