//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderItem
    {
        public int PORequestItem_PK { get; set; }
        public Nullable<int> PurchaseOrder_FK { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<int> ItemQuantity { get; set; }
        public Nullable<double> ItemPrice { get; set; }
        public Nullable<double> ItemExtPrice { get; set; }
    }
}
